home_site_title: "Hey, We're Pavilion."
home_site_description: "We're a freelancer cooperative that works exclusively with <a href='https://discourse.org' class='animated-link' target='_blank'>Discourse</a>."
home_box_1_text: "Hire us to work on your Discourse"
home_box_1_url: "/new-message?groupname=team&title=Consulting%20Enquiry"
home_box_2_text: "Ask about our open source plugins"
home_box_2_url: "/new-message?groupname=team&title=Plugin%20Enquiry"
home_box_3_text: "Join our cooperative"
home_box_3_url: "/new-message?groupname=team&title=Join%20Pavilion"